const fs = require('fs');

const newModules = `  const systemModules = [
    {
      id: "clinical_care",
      labelAr: "الرعاية السريرية",
      labelEn: "Clinical Care",
      icon: Stethoscope,
      hasChildren: true,
      subItems: [
        { id: "doctorworkspace", labelAr: "مساحة عمل الطبيب", labelEn: "Doctor Workspace" },
        { id: "doctorconsultationdesk", labelAr: "استشارات الطبيب", labelEn: "Doctor Consultation Desk" },
        { id: "nurseworkspace", labelAr: "مساحة عمل التمريض", labelEn: "Nurse Workspace" },
        { id: "wardnurse", labelAr: "تمريض الأقسام", labelEn: "Ward Nurse" },
        { id: "er", labelAr: "مساحة عمل الطوارئ", labelEn: "Emergency Workspace" },
        { id: "patient_workspace", labelAr: "مساحة عمل المريض", labelEn: "Patient Workspace" },
        { id: "clinics", labelAr: "العيادات الخارجية", labelEn: "Outpatient Clinics" },
        { id: "clinicslist", labelAr: "قائمة العيادات", labelEn: "Clinics List" },
        { id: "icu", labelAr: "العناية المركزة (ICU)", labelEn: "Intensive Care (ICU)" },
        { id: "nicu", labelAr: "العناية المركزة للأطفال (NICU)", labelEn: "Neonatal ICU (NICU)" },
        { id: "wards", labelAr: "الأقسام الداخلية", labelEn: "Inpatient Wards" },
        { id: "ipd", labelAr: "لوحة التنويم الداخلي", labelEn: "IPD Dashboard" },
        { id: "physicianward", labelAr: "أطباء الباطنة", labelEn: "Physician Ward" },
        { id: "obs_gyn", labelAr: "النساء والولادة", labelEn: "Obstetrics & Gynecology" },
        { id: "pacu", labelAr: "الإفاقة (PACU)", labelEn: "Recovery (PACU)" },
        { id: "operatingtheater", labelAr: "العمليات الجراحية", labelEn: "Operating Theater" },
        { id: "live_consultation", labelAr: "الاستشارات المرئية", labelEn: "Live Consultations" },
        { id: "liveconsultation", labelAr: "لوحة الاستشارات المرئية", labelEn: "Live Consultation Hub" },
        { id: "telemedicine", labelAr: "الطب الاتصالي", labelEn: "Telemedicine" },
        { id: "referral", labelAr: "الإحالات الطبية", labelEn: "Referral Management" },
        { id: "mortuary", labelAr: "شؤون الموتى (المشرحة)", labelEn: "Mortuary" },
        { id: "birthdeathrecord", labelAr: "سجلات المواليد والوفيات", labelEn: "Birth & Death Records" },
        { id: "empi", labelAr: "إدارة الهوية الطبية", labelEn: "Medical Identity" },
        { id: "patientjourneyengine", labelAr: "تتبع مسار المريض", labelEn: "Patient Journey" },
        { id: "patienttrackingkardex", labelAr: "سجل تتبع المريض", labelEn: "Patient Tracking Kardex" },
        { id: "nursingflowkardex", labelAr: "تدفق التمريض", labelEn: "Nursing Flow Kardex" },
        { id: "vitals", labelAr: "العلامات الحيوية", labelEn: "Vitals Dashboard" },
        { id: "nursingdirector", labelAr: "مدير التمريض", labelEn: "Nursing Director" },
        { id: "nursingsupervisor", labelAr: "مشرف التمريض", labelEn: "Nursing Supervisor" },
        { id: "medical_tools", labelAr: "الأدوات الطبية", labelEn: "Medical Tools" },
      ]
    },
    {
      id: "allied_health",
      labelAr: "الخدمات الطبية المساندة",
      labelEn: "Allied Health Services",
      icon: FlaskConical,
      hasChildren: true,
      subItems: [
        { id: "laboratory", labelAr: "المختبر (LIS)", labelEn: "Laboratory (LIS)" },
        { id: "radiology", labelAr: "الأشعة (RIS / PACS)", labelEn: "Radiology (RIS/PACS)" },
        { id: "lisris", labelAr: "نظام LIS/RIS", labelEn: "LIS/RIS Integration" },
        { id: "pathology", labelAr: "علم الأمراض والأنسجة", labelEn: "Pathology" },
        { id: "pt", labelAr: "العلاج الطبيعي والتأهيل", labelEn: "Physical Therapy & Rehab" },
        { id: "nutrition", labelAr: "التغذية العلاجية", labelEn: "Clinical Nutrition" },
        { id: "pharmacy", labelAr: "الصيدلية", labelEn: "Pharmacy" },
        { id: "bloodbank", labelAr: "بنك الدم", labelEn: "Blood Bank" }
      ]
    },
    {
      id: "hospital_operations",
      labelAr: "تشغيل المستشفى",
      labelEn: "Hospital Operations",
      icon: Layers,
      hasChildren: true,
      subItems: [
        { id: "hospital_ops", labelAr: "عمليات المستشفى", labelEn: "Hospital Ops Dashboard" },
        { id: "capacitymanagement", labelAr: "إدارة الطاقة الاستيعابية", labelEn: "Capacity Management" },
        { id: "smartbedallocation", labelAr: "تخصيص الأسرة الذكي", labelEn: "Smart Bed Allocation" },
        { id: "admissioncenter", labelAr: "مركز الدخول", labelEn: "Admission Center" },
        { id: "transport", labelAr: "حركة ونقل المرضى (MOVE)", labelEn: "Patient Transport" },
        { id: "patientmovement", labelAr: "حركة ونقل المرضى (متقدم)", labelEn: "Advanced Patient Movement" },
        { id: "ambulance", labelAr: "الإسعاف", labelEn: "Ambulance" },
        { id: "queuemanagement", labelAr: "إدارة طوابير الانتظار", labelEn: "Queue Management" },
        { id: "assetmanagement", labelAr: "إدارة الأصول", labelEn: "Asset Management" },
        { id: "biomedicalengineering", labelAr: "الهندسة الطبية", labelEn: "Biomedical Engineering" },
        { id: "maintenance", labelAr: "الصيانة والمرافق", labelEn: "Maintenance" },
        { id: "cssd", labelAr: "التعقيم (CSSD)", labelEn: "CSSD" },
        { id: "security", labelAr: "الأمن والسلامة", labelEn: "Security" },
        { id: "meals", labelAr: "وجبات المرضى والموظفين", labelEn: "Meals & Nutrition Log" },
        { id: "mealsdeliverylog", labelAr: "سجل توصيل الوجبات", labelEn: "Meals Delivery Log" },
        { id: "enterpriseinventoryengine", labelAr: "إدارة المخزون المؤسسي", labelEn: "Enterprise Inventory" },
        { id: "purchasingpo", labelAr: "المشتريات", labelEn: "Purchasing & PO" },
        { id: "distribution", labelAr: "التوزيع", labelEn: "Distribution" },
        { id: "gatereception", labelAr: "استقبال البوابة", labelEn: "Gate Reception" },
        { id: "front_office", labelAr: "المكاتب الأمامية", labelEn: "Front Office" },
      ]
    },
    {
      id: "patient_safety_quality",
      labelAr: "سلامة المرضى والجودة",
      labelEn: "Patient Safety & Quality",
      icon: ShieldAlert,
      hasChildren: true,
      subItems: [
        { id: "patientsafetycenter", labelAr: "مركز سلامة المرضى", labelEn: "Patient Safety Center" },
        { id: "medicationsafety", labelAr: "أمان الدواء", labelEn: "Medication Safety" },
        { id: "clinicalalerts", labelAr: "التنبيهات السريرية", labelEn: "Clinical Alerts" },
        { id: "rrt", labelAr: "فريق التدخل السريع (RRT)", labelEn: "Rapid Response Team" },
        { id: "infectionsurveillanceai", labelAr: "مراقبة العدوى بالذكاء الاصطناعي", labelEn: "Infection Surveillance AI" },
        { id: "infectioncontrolhub", labelAr: "مركز مكافحة العدوى", labelEn: "Infection Control Hub" },
        { id: "clinicalprotocolengine", labelAr: "محرك البروتوكولات السريرية", labelEn: "Clinical Protocol Engine" },
        { id: "smartchecklistengine", labelAr: "محرك القوائم الذكية", labelEn: "Smart Checklist Engine" },
        { id: "hospitalpolicycenter", labelAr: "مركز سياسات المستشفى", labelEn: "Hospital Policy Center" },
        { id: "accreditationcenter", labelAr: "مركز الاعتماد والجودة", labelEn: "Accreditation Center" },
        { id: "quality", labelAr: "الجودة والاعتماد", labelEn: "Quality Dashboard" },
        { id: "nationaldbinspector", labelAr: "التدقيق الوطني", labelEn: "National DB Inspector" },
      ]
    },
    {
      id: "admin_finance",
      labelAr: "الإدارة والمالية",
      labelEn: "Administration & Finance",
      icon: Users,
      hasChildren: true,
      subItems: [
        { id: "executiveportal", labelAr: "بوابة الإدارة التنفيذية", labelEn: "Executive Portal" },
        { id: "doctorportal", labelAr: "بوابة الطبيب", labelEn: "Doctor Portal" },
        { id: "billinginsurance", labelAr: "الفوترة والتأمين", labelEn: "Billing & Insurance" },
        { id: "revenuecycle", labelAr: "دورة الإيرادات", labelEn: "Revenue Cycle Dashboard" },
        { id: "financeincomeexpense", labelAr: "الدخل والمصروفات", labelEn: "Finance & Expenses" },
        { id: "cashierpointofsale", labelAr: "الكاشير", labelEn: "Cashier POS" },
        { id: "insurancemaster", labelAr: "إدارة التأمين", labelEn: "Insurance Master" },
        { id: "tpa_management", labelAr: "إدارة TPA", labelEn: "TPA Management" },
        { id: "hr", labelAr: "الموارد البشرية", labelEn: "Human Resources" },
        { id: "rosterplanningpanel", labelAr: "تخطيط الجداول", labelEn: "Roster Planning Panel" },
        { id: "employeeevaluationsystem", labelAr: "تقييم الموظفين", labelEn: "Employee Evaluation" },
        { id: "organization", labelAr: "المؤسسة", labelEn: "Organization Dashboard" },
        { id: "licensemanager", labelAr: "إدارة الرخص", labelEn: "License Manager" },
        { id: "iam", labelAr: "إدارة الهوية والصلاحيات", labelEn: "IAM" },
        { id: "medication_ledger", labelAr: "سجل الأدوية الذكي", labelEn: "Smart Medication Ledger" },
        { id: "medicationledger", labelAr: "سجل الأدوية التفصيلي", labelEn: "Detailed Medication Ledger" },
        { id: "clinicalcalendar", labelAr: "التقويم السريري", labelEn: "Clinical Calendar" },
        { id: "enterprisescheduler", labelAr: "الجدولة المؤسسية", labelEn: "Enterprise Scheduler" },
      ]
    },
    {
      id: "intelligence_ai",
      labelAr: "الذكاء والتحليلات",
      labelEn: "Intelligence & AI",
      icon: Zap,
      hasChildren: true,
      subItems: [
        { id: "missioncontrol", labelAr: "مركز التحكم والقيادة", labelEn: "Mission Control Center" },
        { id: "enterprisecommandcenter", labelAr: "مركز القيادة المؤسسي", labelEn: "Enterprise Command Center" },
        { id: "digitaltwinhospital", labelAr: "المستشفى التوأم الرقمي", labelEn: "Digital Twin Hospital" },
        { id: "digitaltwin", labelAr: "التوأم الرقمي المتقدم", labelEn: "Advanced Digital Twin" },
        { id: "aiclincialbrain", labelAr: "العقل الطبي (AI)", labelEn: "AI Clinical Brain" },
        { id: "aihospitalbrain", labelAr: "عقل المستشفى (AI)", labelEn: "AI Hospital Brain" },
        { id: "aiclinicaldecisionsupport", labelAr: "دعم القرار السريري", labelEn: "AI Decision Support" },
        { id: "predictiveanalytics", labelAr: "التحليلات التنبؤية", labelEn: "Predictive Analytics" },
        { id: "aimedicalscribe", labelAr: "الكاتب الطبي بالذكاء الاصطناعي", labelEn: "AI Medical Scribe" },
        { id: "hospitaldigitalassistant", labelAr: "المساعد الرقمي للمستشفى", labelEn: "Hospital Digital Assistant" },
        { id: "nurseai", labelAr: "الممرضة الذكية", labelEn: "Nurse AI Workspace" },
        { id: "digitalpatient", labelAr: "المريض الرقمي", labelEn: "Digital Patient Twin" },
        { id: "smartwhiteboards", labelAr: "الشاشات البيضاء الذكية", labelEn: "Smart Whiteboards" },
        { id: "enterprisesearch", labelAr: "البحث المؤسسي الشامل", labelEn: "Enterprise Search" },
        { id: "analytics", labelAr: "التحليلات", labelEn: "Analytics Hub" },
        { id: "analyticskpi", labelAr: "مؤشرات الأداء", labelEn: "Analytics KPI" },
      ]
    },
    {
      id: "platform_admin",
      labelAr: "المنصة والإعدادات",
      labelEn: "Platform & Administration",
      icon: Database,
      hasChildren: true,
      subItems: [
        { id: "hospitalkernel", labelAr: "نظام التشغيل والأحداث", labelEn: "Hospital OS Kernel" },
        { id: "master_data", labelAr: "حوكمة البيانات الأساسية", labelEn: "Master Data Gov" },
        { id: "report_center", labelAr: "مركز طباعة التقارير", labelEn: "Enterprise Report Center" },
        { id: "reports", labelAr: "التقارير", labelEn: "Reports Dashboard" },
        { id: "document_center", labelAr: "مركز الوثائق", labelEn: "Document Center" },
        { id: "documentmanager", labelAr: "إدارة الوثائق", labelEn: "Document Manager" },
        { id: "smartformbuilder", labelAr: "باني النماذج", labelEn: "Smart Form Builder" },
        { id: "formeditor", labelAr: "محرر النماذج", labelEn: "Form Editor" },
        { id: "manage_templates", labelAr: "إدارة القوالب", labelEn: "Manage Templates" },
        { id: "audit_center", labelAr: "مركز سجلات التدقيق", labelEn: "Audit Center" },
        { id: "integration_center", labelAr: "مركز التكامل والربط", labelEn: "Integration Hub" },
        { id: "integration", labelAr: "تكاملات النظام", labelEn: "System Integration" },
        { id: "nationalintegrationhub", labelAr: "الربط الوطني", labelEn: "National Integration Hub" },
        { id: "apicenter", labelAr: "مركز الربط البرمجي", labelEn: "API Center" },
        { id: "backup_center", labelAr: "النسخ الاحتياطي والأرشفة", labelEn: "Backup & Recovery" },
        { id: "disasterrecovery", labelAr: "التعافي من الكوارث", labelEn: "Disaster Recovery" },
        { id: "permissions_matrix", labelAr: "مصفوفة الصلاحيات المتقدمة", labelEn: "Permissions Matrix" },
        { id: "enterprisenotificationcenter", labelAr: "مركز الإشعارات الموحد", labelEn: "Notification Engine" },
        { id: "clinicalcommunication", labelAr: "التواصل السريري", labelEn: "Clinical Communication" },
        { id: "messaging", labelAr: "المراسلات الداخلية", labelEn: "Messaging" },
        { id: "medicalknowledgebase", labelAr: "القاعدة المعرفية الطبية", labelEn: "Medical Knowledge Base" },
        { id: "escalationengine", labelAr: "محرك التصعيد التلقائي", labelEn: "Escalation Engine" },
        { id: "hospitalrulesengine", labelAr: "محرك قواعد المستشفى", labelEn: "Hospital Rules Engine" },
        { id: "universaltaskengine", labelAr: "محرك المهام الشامل", labelEn: "Universal Task Engine" },
        { id: "tasks", labelAr: "المهام", labelEn: "Tasks Dashboard" },
        { id: "workflow_designer", labelAr: "مصمم مسارات العمل", labelEn: "Workflow Designer" },
        { id: "workflow", labelAr: "مسارات العمل", labelEn: "Workflow Dashboard" },
        { id: "wf_reception", labelAr: "مسار الاستقبال", labelEn: "Reception Workflow" },
        { id: "wf_er", labelAr: "مسار الطوارئ (ER)", labelEn: "ER Workflow" },
        { id: "wf_clinic", labelAr: "مسار العيادات", labelEn: "Outpatient Workflow" },
        { id: "wf_inpatient", labelAr: "مسار التنويم", labelEn: "Inpatient Workflow" },
        { id: "wf_ot", labelAr: "مسار العمليات (OT)", labelEn: "OT Workflow" },
        { id: "wf_icu", labelAr: "مسار العناية (ICU)", labelEn: "ICU Workflow" },
        { id: "wf_diagnostics", labelAr: "مسار المختبر والأشعة", labelEn: "Diagnostics Hub" },
        { id: "wf_pharmacy", labelAr: "مسار الصيدلية", labelEn: "Pharmacy Hub" },
        { id: "wf_inventory", labelAr: "مسار المخازن", labelEn: "Inventory Hub" },
        { id: "wf_cpoe", labelAr: "الطلبات الطبية (CPOE)", labelEn: "CPOE Flow" },
        { id: "cybersecurityhub", labelAr: "الأمن السيبراني", labelEn: "Cyber Security Hub" },
        { id: "platformengines", labelAr: "محركات المنصة", labelEn: "Platform Engines" },
        { id: "specializedmodules", labelAr: "الأنظمة المتخصصة", labelEn: "Specialized Modules" },
        { id: "global_settings", labelAr: "الإعدادات العامة", labelEn: "Global Settings" },
        { id: "hisprofileworkspace", labelAr: "الملف الشخصي", labelEn: "Profile Workspace" },
        { id: "download_center", labelAr: "مركز التنزيلات", labelEn: "Download Center" },
        { id: "front_cms", labelAr: "نظام إدارة المحتوى", labelEn: "Front CMS" },
      ]
    }
  ];
  const [expandedModules, setExpandedModules] = useState<string[]>(["clinical_care", "intelligence_ai"]);`;

let fileStr = fs.readFileSync('src/components/HospitalInformationSystem.tsx', 'utf8');
const regex = /const systemModules = \[[\s\S]*?\];\n\s*const \[expandedModules, setExpandedModules\] = useState<string\[\]>\(\[.*?\]\);/m;

if (regex.test(fileStr)) {
  const updatedStr = fileStr.replace(regex, newModules);
  fs.writeFileSync('src/components/HospitalInformationSystem.tsx', updatedStr);
  console.log("Success: Modules updated");
} else {
  console.log("Error: regex did not match");
}
